trigger:
  branches:
    include:
      - main  # Ejecutar cuando haya cambios en main

variables:
  NODE_VERSION: '18.x'  # Versión de Node.js
  BACKEND_APP_SERVICE: 'tfBackNotif'  # Nombre de tu App Service en Azure
  AZURE_SUBSCRIPTION: 'Azure for Students(b1a9be0c-3adb-4b54-9b44-14b4d64810e1)'

stages:
- stage: Build
  displayName: 'Build Backend'
  jobs:
  - job: Build_Backend
    displayName: 'Instalar dependencias y preparar backend'
    pool:
      name: Default
      demands:
      - agent.name -equals pool1
    steps:
    - checkout: self

    - task: UseNode@1
      inputs:
        version: $(NODE_VERSION)

    - script: |
        cd backend_sistema_notificaciones
        npm install
      displayName: 'Instalar dependencias'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'backend_sistema_notificaciones'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/backend.zip'
        artifactName: 'backend'

- stage: Deploy
  displayName: 'Deploy Backend to Azure'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy_Backend
    displayName: 'Desplegar Backend en Azure App Service'
    environment: 'production'
    pool:
      name: Default
      demands:
      - agent.name -equals pool1
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              artifactName: 'backend'
              downloadPath: '$(Build.ArtifactStagingDirectory)'

          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy Backend'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Azure for Students(b1a9be0c-3adb-4b54-9b44-14b4d64810e1)'
              appType: 'webAppLinux'
              WebAppName: 'tfnotif-back'
              packageForLinux: '$(Build.ArtifactStagingDirectory)/backend.zip'
              RuntimeStack: 'NODE|18-lts'
              StartupCommand: 'npm start'
