trigger:
  branches:
    include:
      - main  # Ejecutar cuando haya cambios en main

variables:
  NODE_VERSION: '18.x'  # Versión de Node.js
  BACKEND_APP_SERVICE: 'tfBackNotif'
  FRONTEND_APP_SERVICE: 'tfFrontNotif'
  AZURE_SUBSCRIPTION: 'Azure for Students(b1a9be0c-3adb-4b54-9b44-14b4d64810e1)'

stages:
- stage: BuildBack
  displayName: 'Build Backend'
  jobs:
  - job: Build_Backend
    displayName: 'Instalar dependencias y preparar backend'
    pool:
      name: Default
      demands:
      - agent.name -equals pool1
    steps:
    - checkout: self

    - task: UseNode@1
      inputs:
        version: $(NODE_VERSION)

    - script: |
        cd backend_sistema_notificaciones
        npm install
      displayName: 'Instalar dependencias'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'backend_sistema_notificaciones'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/backend.zip'
        artifactName: 'backend'

- stage: BuildFront
  displayName: 'Build Frontend'
  jobs:
  - job: Build_Frontend
    displayName: 'Instalar dependencias y preparar front'
    pool:
      name: Default
      demands:
      - agent.name -equals pool1
    steps:
    - checkout: self

    - task: UseNode@1
      inputs:
        version: $(NODE_VERSION)

    - script: |
        cd .\frontend-sistema-notificaciones\ 
        npm install
      displayName: 'Instalar dependencias y construir frontend'

    - task: PowerShell@2
      inputs:
        filePath: '$(Build.ArtifactStagingDirectory)/'
        arguments: 'cd .\frontend-sistema-notificaciones\; npm run build'
    
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'frontend_sistema_notificaciones/.next'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/frontend.zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/frontend.zip'
        artifactName: 'frontend'

- stage: DeployBackend
  displayName: 'Deploy Backend to Azure'
  dependsOn: BuildBack
  condition: succeeded()
  jobs:
  - deployment: Deploy_Backend
    displayName: 'Desplegar Backend en Azure App Service'
    environment: 'production'
    pool:
      name: Default
      demands:
      - agent.name -equals pool1
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              artifactName: 'backend'
              downloadPath: '$(Build.ArtifactStagingDirectory)'

          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy Backend'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Azure for Students(af4c3a90-6ae3-45fb-a39a-e727038433fc)'
              appType: 'webAppLinux'
              WebAppName: 'back-prue'
              packageForLinux: '$(Build.ArtifactStagingDirectory)/backend/backend.zip'
              RuntimeStack: 'NODE|18-lts'
              StartupCommand: 'npm start'

- stage: DeployFront
  displayName: 'Deploy Frontend to Azure'
  dependsOn: BuildFront
  condition: succeeded()
  jobs:
  - deployment: Deploy_Frontend
    displayName: 'Desplegar Frontend en Azure App Service'
    environment: 'production'
    pool:
      name: Default
      demands:
      - agent.name -equals pool1
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              artifactName: 'frontend'
              downloadPath: '$(Build.ArtifactStagingDirectory)'

          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy Frontend'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Azure for Students(af4c3a90-6ae3-45fb-a39a-e727038433fc)'
              appType: 'webAppLinux'
              WebAppName: 'front-prue'
              packageForLinux: '$(Build.ArtifactStagingDirectory)/frontend/frontend.zip'
              RuntimeStack: 'NODE|18-lts'
              StartupCommand: 'npx next start -p 8080'
