trigger:
- main

pr:
  branches:
    include:
      - main
pool:
  name: default
  demands:
  - agent.name -equals pool1

stages:
  - stage: Register_Backend
    displayName: "construir y desplegar backend en Container Registry"
    jobs:
      - job: Build_Backend_Container
        steps:
        - task: UseNode@1
          inputs:
            version: '20.x'
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'Azure for Students(be47ff6d-9100-47c2-ab9a-af967aabfd60)'
            scriptType: 'ps'
            scriptLocation: 'inlineScript'
            inlineScript: 'az acr login --name $(CONTAINER_REGISTRY_URL)'
        - task: CmdLine@2
          inputs:
            script: |
              echo "DB_USERNAME=$(DB_USERNAME)" > backend_sistema_notificaciones/.env
              echo "DB_PASSWORD=$(DB_PASSWORD)" >> backend_sistema_notificaciones/.env
              echo "DB_DATABASE=$(DB_DATABASE)" >> backend_sistema_notificaciones/.env
              echo "DB_HOST=$(DB_HOST)" >> backend_sistema_notificaciones/.env
              echo "DB_PORT=$(DB_PORT)" >> backend_sistema_notificaciones/.env
              echo "DB_DIALECT=$(DB_DIALECT)" >> backend_sistema_notificaciones/.env
              echo "DB_OPERATOR_ALIASES=$(DB_OPERATOR_ALIASES)" >> backend_sistema_notificaciones/.env
              echo "NODE_ENV=$(NODE_ENV)" >> backend_sistema_notificaciones/.env
              echo "KEY_SQ=$(KEY_SQ)" >> backend_sistema_notificaciones/.env
              echo "LOGIC_APPS_URL=$(LOGIC_APPS_URL)" >> backend_sistema_notificaciones/.env
            workingDirectory: $(Build.SourcesDirectory)
          displayName: "Crear archivo .env"
        - task: CmdLine@2
          inputs:
            script: |
              cd backend_sistema_notificaciones
              docker build --env-file .env -t $(CONTAINER_REGISTRY_URL)/backend-notificaciones:$(BACKEND_TAG) .
          displayName: "construir imagen del backend"
        
        - task: CmdLine@2
          inputs:
            script: 'docker push $(CONTAINER_REGISTRY_URL)/backend-notificaciones:$(BACKEND_TAG)'
          displayName: "Registrar Backend a Container Registry"
  - stage: Deploy_backend
    displayName: "Desplegar contenedor de backend a Container App"
    dependsOn: Register_Backend
    jobs:
      - job: Release_backend_container
        steps:
          - task: AzureContainerApps@1
            inputs:
              azureSubscription: 'Azure for Students(be47ff6d-9100-47c2-ab9a-af967aabfd60)'
              acrName: '$(CONTAINER_REGISTRY_URL)'
              imageToDeploy: '$(CONTAINER_REGISTRY_URL)/backend-notificaciones:$(BACKEND_TAG)'
              containerAppName: 'tf-backend'
              resourceGroup: 'TrabajoFinalCloud'
              targetPort: '8000'