version: '3.9'

services:
  backend:
    build: ./backend_sistema_notificaciones
    container_name: backend_sistema_notificaciones
    restart: always
    environment:
      - NODE_ENV=development
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DIALECT=${DB_DIALECT}
      - DB_OPERATOR_ALIASES=${DB_OPERATOR_ALIASES}
      - KEY_SQ=${KEY_SQ}
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - app_network

  frontend:
    build: ./frontend-sistema-notificaciones
    container_name: frontend_sistema_notificaciones
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

  database:
    image: mysql:8.0
    container_name: mysql_notificacion_bd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root12345
      MYSQL_DATABASE: NotificacionBD
      MYSQL_USER: BDFinalNoti
      MYSQL_PASSWORD: final@12345
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge